name: 📋 Code Pattern Issue (Automated) 
description: Automatically detected code pattern that needs attention
title: "[CODE-PATTERN] {pattern_type}: {location}"
labels: ["code-quality", "automated", "pattern-detection"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **🤖 This issue was automatically created by a Copilot agent after detecting a code pattern that may need attention.**
        
  - type: dropdown
    id: pattern_type
    attributes:
      label: Pattern Type
      description: What type of code pattern was detected?
      options:
        - TODO/FIXME comments
        - Deprecated API usage
        - Code duplication
        - Performance anti-pattern
        - Security anti-pattern
        - Error handling issue
        - Documentation gap
        - Test coverage gap
        - Other
    validations:
      required: true
      
  - type: input
    id: location
    attributes:
      label: Location
      description: Where in the codebase was this pattern found?
      placeholder: "e.g., src/main/java/UserService.java:125"
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent is addressing this pattern?
      options:
        - Low - Improvement opportunity
        - Medium - Should be addressed
        - High - Important to fix
        - Critical - Must be fixed soon
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Pattern Description
      description: Detailed description of what was detected
      placeholder: "Describe the specific pattern, why it might be problematic, and any context..."
    validations:
      required: true
      
  - type: textarea
    id: code_excerpt
    attributes:
      label: Code Excerpt
      description: Relevant code snippet showing the pattern
      render: java
      placeholder: |
        // Example:
        public void processUser() {
            // TODO: Add proper error handling here
            user.save(); // This could throw an exception
        }
    validations:
      required: false
      
  - type: textarea
    id: suggested_solution
    attributes:
      label: Suggested Solution
      description: What actions could be taken to address this pattern?
      placeholder: |
        - Implement proper error handling
        - Replace deprecated method with new API
        - Refactor to reduce duplication
        - Add missing tests
        - etc.
    validations:
      required: false
      
  - type: input
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: What could happen if this pattern is not addressed?
      placeholder: "e.g., Potential runtime errors, maintenance difficulties, security risks"
    validations:
      required: false
      
  - type: checkboxes
    id: automation_info
    attributes:
      label: Detection Information
      description: Automatically generated information about the detection
      options:
        - label: Pattern detected by automated analysis
          required: false
        - label: Multiple occurrences may exist
          required: false
        - label: Requires human review for context
          required: false