name: 🔐 Security Vulnerability (Automated)
description: Automatically detected security vulnerability that needs attention
title: "[SECURITY] {vulnerability_type}: {component_name}"
labels: ["security", "vulnerability", "automated", "priority-high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ This issue was automatically created by a Copilot agent after detecting a potential security vulnerability.**
        
  - type: input
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability was detected?
      placeholder: "e.g., Dependency vulnerability, Code injection, XSS, etc."
    validations:
      required: true
      
  - type: input
    id: component_name
    attributes:
      label: Affected Component
      description: Which component, dependency, or code section is affected?
      placeholder: "e.g., jackson-databind:2.17.0, UserInput.java:42"
    validations:
      required: true
      
  - type: input
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      placeholder: "e.g., Critical, High, Medium, Low"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the vulnerability
      placeholder: "Describe the vulnerability, its potential impact, and any relevant CVE numbers..."
    validations:
      required: true
      
  - type: textarea
    id: evidence
    attributes:
      label: Evidence/Location
      description: Where was this vulnerability found? Include file paths, line numbers, or dependency information.
      placeholder: |
        File: src/main/java/example/UserController.java
        Line: 42
        Code: String userInput = request.getParameter("input"); // Potential XSS
        
        OR
        
        Dependency: jackson-databind:2.17.0
        CVE: CVE-2023-XXXXX
    validations:
      required: true
      
  - type: textarea
    id: remediation
    attributes:
      label: Suggested Remediation
      description: What actions should be taken to fix this vulnerability?
      placeholder: |
        - Update dependency to version X.X.X or later
        - Implement input validation/sanitization
        - Add security controls
        - etc.
    validations:
      required: false
      
  - type: input
    id: references
    attributes:
      label: References
      description: Links to CVE databases, security advisories, or documentation
      placeholder: "https://nvd.nist.gov/vuln/detail/CVE-2023-XXXXX"
    validations:
      required: false
      
  - type: checkboxes
    id: automation_info
    attributes:
      label: Automation Information
      description: This section is automatically filled by the Copilot agent
      options:
        - label: This issue was created by an automated security scan
          required: false
        - label: The detection rules used are up-to-date
          required: false
        - label: Manual verification is recommended
          required: false