@startuml
title Engine Package Structure

package "september.engine" {
  package "core"
  package "ecs"
  package "assets"
  package "audio"
  package "rendering"
  package "state"
  package "systems"
}

@enduml
