name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Build and Test with Docker
      run: |
        # Build the Docker image that contains all dependencies and the correct environment
        docker build -t september-ci .

        # Run the tests inside the container.
        # We mount the target directory to make reports and artifacts available to subsequent steps.
        # We also mount the .m2 directory to leverage the runner's cache inside the container.
        docker run --rm \
          -v "${{ github.workspace }}/target:/workspace/target" \
          -v "~/.m2:/root/.m2" \
          september-ci

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      if: github.event_name == 'pull_request' && always()
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        title: 'JaCoCo Coverage Report'
        update-comment: true

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() && hashFiles('**/target/surefire-reports/TEST-*.xml') != ''
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
        check_name: 'Test Results'
        fail_on_failure: false

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: september-linux-artifacts
        path: target/september-*.jar
        retention-days: 30

  publish:
    needs: build
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github

    - name: Publish to GitHub Packages
      run: mvn -B deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/september-linux-artifacts/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
